version: '3.9'
services:
  build_buxfuse:
    build:
      context: ./buxfuse-custom
    volumes:
      - /my_volume:/app/boxfuse-sample-java-war-hello/target
    networks:
      - webnet

  prod:
    image: tomcat:9-jdk11-slim
    ports:
      - "8090:8080"
    volumes:
      - /my_volume:/usr/local/tomcat/webapps
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  my_volume:
  app: