version: '3.9'
services:
  build_buxfuse:
    build:
      context: ./buxfuse-custom
    volumes:
      - type: volume
        source: app_volume
        target: /app_volue

  prod:
    image: tomcat:9-jdk11-slim
    ports:
      - "8090:8080"
    volumes:
      - "/app_volume/boxfuse-sample-java-war-hello/target/hello-1.0.war:/usr/local/tomcat/webapps/hello-1.0.war"

volumes:
  app_volume: