version: '3'
services:
  build_buxfuse:
    build:
      context: ./buxfuse-custom
    volumes:
      - my_volume:/app/boxfuse-sample-java-war-hello/target
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  my_volume: