version: '3'
services:
  build_buxfuse:
    build:
      context: ./buxfuse-custom
    volumes:
      - my_volume:/app/boxfuse-sample-java-war-hello/target

  prod:
    image: tomcat:9-jdk11-slim
    ports:
      - "8090:8080"
    volumes:
      - my_volume:/usr/local/tomcat/webapps
    depends_on:
      - build_buxfuse

volumes:
  my_volume: