version: '3.8'
services:
  build_buxfuse:
    build:
      context: ./buxfuse-custom
    volumes:
      - type: volume
        source: my_volume
        target: /app/boxfuse-sample-java-war-hello/target
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  my_volume: