version: '3.9'
services:
  web:
    image: tomcat:latest-slim
    ports:
      - "8090:8080"
    volumes:
      - "/app_volume/boxfuse-sample-java-war-hello/target/hello-1.0.war:/var/lib/tomcat9/webapps/hello-1.0.war"

  buxfuse:
    build: buxfuse-custom
    volumes:
      - "/app_volume:/app_volume"

volumes:
  app_volume: